mode: daemonset

config:
  exporters:
    datadog:
      api:
        key: "${datadog_api_key}"
        site: "${datadog_site}"
  processors:
    batch:
      send_batch_size: 1000
      timeout: 10s
    datadog:
    k8sattributes/default:
    memory_limiter:
      check_interval: 1s
      limit_percentage: 75
      spike_limit_percentage: 15
    probabilistic_sampler:
      sampling_percentage: 20
    resourcedetection/system:
      detectors: [env, system, gcp, ec2, azure]
      timeout: 2s
    override: false
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
        http:
          endpoint: ${env:MY_POD_IP}:4318
    statsd:
      endpoint: ${env:MY_POD_IP}:8125
      aggregation_interval: 60s
      enable_metric_type: true
      timer_histogram_mapping:
        - statsd_type: "histogram"
          observer_type: "gauge"
        - statsd_type: "timing"
          observer_type: "histogram"
          histogram:
            max_size: 170
        - statsd_type: "distribution"
          observer_type: "histogram"
          histogram:
            max_size: 170
  service:
    extensions: [health_check, memory_ballast, pprof, zpages ]
    pipelines:
      metrics:
        exporters:
          - datadog
        processors:
          - memory_limiter
          - batch
        receivers:
          - datadog/connector
          - otlp
          - statsd
      traces:
        exporters:
          - datadog/connector
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      traces/2:
        exporters:
          - datadog
        processors:
          - memory_limiter
          - batch
          - probabilistic_sampler
        receivers:
          - otlp


ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
    appProtocol: grpc
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP
  statsd:
    enabled: true
    containerPort: 8125
    servicePort: 8125
    hostPort: 8125
    protocol: UDP


presets:
  logsCollection:
    enabled: false
  hostMetrics:
    enabled: true
  kubernetesAttributes:
    enabled: true
    extractAllPodLabels: true
    extractAllPodAnnotations: false
  kubeletMetrics:
    enabled: false
  kubernetesEvents:
    enabled: false
  clusterMetrics:
    enabled: false

resources:
  limits:
    cpu: 800m
    memory: 1024Mi


